services:
  microservice.authentication.api:
    container_name: microservice.authentication.api
    image: ${DOCKER_REGISTRY-}microserviceauthentication    
    build:
      context: .
      dockerfile: Microservice.Authentication.Api/Dockerfile
    ports: 
      - "12000:8080"
      - "12001:8081"
    environment: 
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_URLS: https://+:8081;http://+:8080
        ASPNETCORE_HTTPS_PORT: 8081   
        JWT_ISSUER: ${JWT_ISSUER}
        JWT_AUDIENCE: ${JWT_AUDIENCE}
        JWT_SYMMETRIC_SECURITY_KEY: ${JWT_SYMMETRIC_SECURITY_KEY} 
    networks:
      - ms-order-system  
  
networks:
  ms-order-system: 
    external: true 