# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - prod-ap-ms-order-authentication

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://prodcrmsordersystem.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_a9c9dd14dc204e72be4646b672eb0c0f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c5bdc80f663c4f5ab9fc623ac4909b5d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: prodcrmsordersystem.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a9c9dd14dc204e72be4646b672eb0c0f }}/microserviceauthentication:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'prod-ap-ms-order-authentication'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_880bbbcdf9e148acb5022a2ceb127c00 }}
        images: 'prodcrmsordersystem.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a9c9dd14dc204e72be4646b672eb0c0f }}/microserviceauthentication:${{ github.sha }}'